version: "3.9"
services:
  postgresql:
    container_name: postgresql
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw


volumes:
  postgres-data:
    driver: local